### ISSUE TITLE
Ethics Templates

### ISSUE THREAD

**Issue by paiva** [CONP-PCNO/Ethics_and_Data_Governance#1]
Perhaps the hardest part in sharing a dataset is to get the Ethics part approved and on point. If we were to provide templates/examples on how to get a study approved in the CONP portal, somewhere, it would facilitate the sharing of a dataset.

**Comment by juriste** [comment]
Bonjour ! Here is our shiny new ethics toolkit - https://github.com/CONP-PCNO/Ethics_and_Data_Governance
